//! Test runner script
//! Run with: cargo test -- --test-threads=1

fn main() {
    // This function is automatically generated by cargo test
    // You can add custom test setup here if needed
    println!("Running CFP System Tests...");
    
    // Set test environment variables
    std::env::set_var("APP_ENVIRONMENT", "test");
    std::env::set_var("DATABASE_URL", "sqlite::memory:");
    std::env::set_var("JWT_SECRET", "test_secret_key_for_testing_only");
    
    // Run tests
    let test_result = std::process::Command::new("cargo")
        .args(["test", "--", "--test-threads=1", "--nocapture"])
        .status()
        .expect("Failed to run tests");
    
    if !test_result.success() {
        std::process::exit(1);
    }
}
